---

- name: Configure | create configuration directory
  ansible.builtin.file:
    path: /etc/rstudio-connect
    state: directory
    mode: '0755'

- name: Configure | write encryption key to file
  ansible.builtin.copy:
    content: "{{ rstudio_encryption_key | trim }}"
    dest: "{{ rstudio_connect_encryption_key_location }}"
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_encryption_key is defined
    - rstudio_encryption_key|length
  tags:
    - rstudio-connect-encryption-key

- name: Configure | create (SSO metadata xml) file
  ansible.builtin.copy:
    content: "{{ rstudio_connect_sso_saml_metadata_content_b64_encoded | b64decode }}"
    dest: "{{ rstudio_connect_sso_saml_metadata_file_path }}"
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_connect_sso_saml_metadata_content_b64_encoded|d()
    - rstudio_connect_sso_saml_metadata_file_path|d()

- name: Configure | create (server) configuration file
  ansible.builtin.template:
    src: etc/rstudio-connect/rstudio-connect.gcfg.j2
    dest: /etc/rstudio-connect/rstudio-connect.gcfg
    owner: root
    group: root
    mode: 0644
  notify: Restart rstudio-connect
  tags:
    - rstudio-connect-configure-server
