---

- name: configure | write encryption key to file
  copy:
    content: "{{ rstudio_encryption_key | trim }}"
    dest: "{{ rstudio_connect_encryption_key_location }}"
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_encryption_key is defined
    - rstudio_encryption_key|length
  tags:
    - rstudio-connect-encryption-key

- name: link systemd default environment file to /etc/environment
  file:
    src: /etc/environment
    dest: /etc/default/rstudio-connect
    state: link
    owner: root
    group: root
  notify: restart rstudio-connect
  tags:
    - rstudio-connect-configure-environment-file

- name: configure | update (server) configuration file
  template:
    src: etc/rstudio-connect/rstudio-connect.gcfg.j2
    dest: /etc/rstudio-connect/rstudio-connect.gcfg
    owner: root
    group: root
    mode: 0644
  notify: restart rstudio-connect
  tags:
    - rstudio-connect-configure-server

- name: configure | update (server) migration file
  template:
    src: etc/rstudio-connect/rstudio-connect-migration.gcfg.j2
    dest: /etc/rstudio-connect/rstudio-connect-migration.gcfg
    owner: root
    group: root
    mode: 0644
  notify: restart rstudio-connect
  tags:
    - rstudio-connect-configure-migration

- name: configure | activate server license
  shell: |
    /opt/rstudio-connect/bin/license-manager activate {{ rstudio_connect_license }}
  notify: restart rstudio-connect
  when: rstudio_connect_license|d()
  register: license_output
  tags:
    - rstudio-connect-configure-license
