---

- name: Configure | write encryption key to file
  ansible.builtin.copy:
    content: "{{ rstudio_encryption_key | trim }}"
    dest: "{{ rstudio_connect_encryption_key_location }}"
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_encryption_key is defined
    - rstudio_encryption_key|length
  tags:
    - rstudio-connect-encryption-key

- name: Configure | create (SSO metadata xml) file
  ansible.builtin.copy:
    content: "{{ rstudio_connect_sso_saml_metadata_content_b64_encoded | b64decode }}"
    dest: "{{ rstudio_connect_sso_saml_metadata_file_path }}"
    owner: root
    group: root
    mode: 0600
  when:
    - rstudio_connect_sso_saml_metadata_content_b64_encoded|d()
    - rstudio_connect_sso_saml_metadata_file_path|d()

- name: Link systemd default environment file to /etc/environment
  ansible.builtin.file:
    src: /etc/environment
    dest: /etc/default/rstudio-connect
    state: link
    owner: root
    group: root
  notify: Restart rstudio-connect
  tags:
    - rstudio-connect-configure-environment-file

- name: Configure | discover Python versions
  block:
    - name: Configure | find directories with Python
      ansible.builtin.find:
        paths: "{{ python_main_directory }}"
        recurse: false
        file_type: directory
      register: python_paths

    - name: Configure | set discovered_python_executables
      ansible.builtin.set_fact:
        # [objects] -> ['/opt/python/3.10.6',...] ->  [['/opt/python/3.10.6','/bin/python3'],...] -> ['/opt/python/3.10.6/bin/python3',...]
        discovered_python_executables: "{{ python_paths.files | map(attribute='path') | product([python_sufix_bin]) | map('join') }}"

    # admin specified python_versions - get only matching executable paths
    - name: Configure | set (filtered) executables
      ansible.builtin.set_fact:
        python_executables: "{{ python_executables | d([]) + [item] }}"
      loop: "{{ discovered_python_executables }}"
      # spliting item: '/opt/python/3.10.6/bin/python3' -> ['', '3.10.6/bin/python3'] ->
      # -> '3.10.6/bin/python3' -> ['3.10.6', ''] -> '3.10.6'
      when: python_versions | length != 0 and (item.split(python_main_directory)[1].split(python_sufix_bin)[0] in python_versions)

    # admin not specified python_versions - get all executable paths
    - name: Configure | set (unfiltered) executables
      ansible.builtin.set_fact:
        python_executables: "{{ discovered_python_executables }}"
      when: python_versions | length == 0

    - name: Configure | set rstudio_connect_python_executables
      ansible.builtin.set_fact:
        rstudio_connect_python_executables: "{{ python_executables }}"

  # discover Python executables only if admin doesn't specify concrete paths in rstudio_connect_python_executables
  when: rstudio_connect_enable_python and (rstudio_connect_python_executables is not defined or rstudio_connect_python_executables | length == 0)
  tags:
    - rstudio-connect-configure-discover-python-executables

- name: Configure | update (server) configuration file
  ansible.builtin.template:
    src: etc/rstudio-connect/rstudio-connect.gcfg.j2
    dest: /etc/rstudio-connect/rstudio-connect.gcfg
    owner: root
    group: root
    mode: 0644
  notify: Restart rstudio-connect
  tags:
    - rstudio-connect-configure-server

- name: Configure | update (server) migration file
  ansible.builtin.template:
    src: etc/rstudio-connect/rstudio-connect-migration.gcfg.j2
    dest: /etc/rstudio-connect/rstudio-connect-migration.gcfg
    owner: root
    group: root
    mode: 0644
  notify: Restart rstudio-connect
  tags:
    - rstudio-connect-configure-migration

- name: License activation (offline)
  block:
    - name: License activation (offline) | upload key file
      ansible.builtin.copy:
        content: "{{ rstudio_connect_license_offline_key_b64_encoded | b64decode }}"
        dest: "/etc/rstudio-connect/activation-key.lic"
        owner: root
        group: root
        mode: 0600

    - name: License activation (offline) | activate using key file  # noqa no-changed-when
      ansible.builtin.shell: |
        /opt/rstudio-connect/bin/license-manager activate-file /etc/rstudio-connect/activation-key.lic
  when: rstudio_connect_license_offline_key_b64_encoded | d()
  notify: Restart rstudio-connect
  no_log: true

- name: License activation (online) | activate key
  ansible.builtin.shell: |
    /opt/rstudio-connect/bin/license-manager activate {{ rstudio_connect_license }}
  notify: Restart rstudio-connect
  register: license_output
  when: rstudio_connect_license | d()
  no_log: true
