# tasks file
---

- name: Include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-include-variables

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-install
  notify: Restart rstudio-connect

- name: Include configure tasks
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-configure

- name: Include install drivers tasks
  ansible.builtin.include_tasks: install-drivers.yml
  when: rstudio_connect_pro_drivers_install

- name: Start and enable service
  ansible.builtin.service:
    name: rstudio-connect
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rtudio-connect
    - rstudio-connect-start-enable-service
