# tasks file
---

- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-include-variables

- include: install.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-install
  notify: restart rstudio-connect

- include: configure.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-configure

- include: install-r.yml
  tags:
    - r-version-install

- include: install-drivers.yml
  when: rstudio_connect_pro_drivers_install

- include: activate-license.yml
  when: rstudio_connect_license|d() or
        rstudio_connect_license_offline_key_b64_encoded|d()

- name: start and enable service
  service:
    name: rstudio-connect
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rtudio-connect
    - rstudio-connect-start-enable-service
