# tasks file
---
- name: Include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ (ansible_distribution + '-' + ansible_distribution_major_version) | lower }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-include-variables

- name: Include configure tasks
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-configure

- name: Import install tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}/main.yml"
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-install

- name: Link systemd default environment file to /etc/environment
  ansible.builtin.file:
    src: /etc/environment
    dest: /etc/default/rstudio-connect
    state: link
    owner: root
    group: root
  notify: Restart rstudio-connect
  tags:
    - rstudio-connect-configure-environment-file

- name: Get rstudio-connect user info
  ansible.builtin.getent:
    database: passwd
    key: "rstudio-connect"

- name: Extract UID and GID
  ansible.builtin.set_fact:
    connect_uid: "{{ getent_passwd['rstudio-connect'][1] }}"
    connect_gid: "{{ getent_passwd['rstudio-connect'][2] }}"

- name: Include user tasks
  ansible.builtin.include_tasks: user.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-configure
  when:
    - rstudio_connect_user_id is defined or rstudio_connect_group_id is defined
    - rstudio_connect_user_id > 0 or rstudio_connect_group_id > 0
    - rstudio_connect_user_id != (connect_uid | int) or rstudio_connect_group_id != (connect_gid | int)
  tags:
    - rstudio-connect-configure-user

- name: Include license tasks
  ansible.builtin.include_tasks: license.yml
  tags:
    - configuration
    - rstudio-connect
    - rstudio-connect-configure

- name: Start and enable service
  ansible.builtin.service:
    name: rstudio-connect
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rtudio-connect
    - rstudio-connect-start-enable-service
