---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - &instance
    name: instance-rsc
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
    platform: linux/amd64
  - <<: *instance
    name: instance-rh
    image: "registry.access.redhat.com/${MOLECULE_DISTRO:-ubi9}/ubi-init"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
