---
- name: Prepare the system for RStudio Connect
  hosts: all
  tasks:
    # Install R for Debian
    - name: Install R from package
      ansible.builtin.apt:
        name: r-base
        update_cache: true
      when: ansible_os_family == 'Debian'

    # Install R and dependencies for RHEL 9 using temporary CRB and EPEL repos
    - name: Install R and dependencies using temporary CRB and EPEL repositories
      ansible.builtin.dnf:
        name:
          - R
          - R-devel
        enablerepo: "epel,codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
      when: ansible_distribution == "RedHat"
      allowerasing: true
