---
- name: Verify
  hosts: all
  pre_tasks:
    - name: Include pre-tasks
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../tests/tasks/verify-common-pre.yml"
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../tests/tasks/verify-common.yml"
