---
- name: Verify
  hosts: all
  become: true
  pre_tasks:
    - name: Include pre-tasks
      include: "{{ playbook_dir }}/../../tests/tasks/verify-common-pre.yml"
  tasks:
    - name: Include tasks
      include: "{{ playbook_dir }}/../../tests/tasks/verify-common.yml"
