# tasks file
---
- name: Install | dependencies
  ansible.builtin.apt:
    name: "{{ rstudio_connect_dependencies }}"
    state: "{{ package_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - rstudio-connect-install-dependencies

- name: Install | additional
  ansible.builtin.package:
    name: "{{ rstudio_connect_install }}"
    state: "{{ package_install_state | default('latest') }}"
  tags:
    - rstudio-connect-install-additional

- name: Install | create (download) directory
  ansible.builtin.file:
    path: "{{ rstudio_connect_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - rstudio-connect-install-download
    - rstudio-connect-install-download-directory

- name: Install | download deb
  ansible.builtin.get_url:
    url: "{{ rstudio_connect_download_url }}"
    dest: "{{ rstudio_connect_downloads_path }}/rstudio-connect-{{ rstudio_connect_version }}-{{ rstudio_connect_machine_map[ansible_machine] }}.deb"
    mode: '0755'

- name: Install | install deb
  ansible.builtin.apt:
    deb: "{{ rstudio_connect_downloads_path }}/rstudio-connect-{{ rstudio_connect_version }}-{{ rstudio_connect_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-connect-install-install
    - rstudio-connect-install-install-deb
