---
# tasks/main.yml

# 1) Enable CodeReady Builder (RHEL 9 only)
- name: Enable CRB
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "9"
  ansible.builtin.dnf_repository:
    name: crb
    enabled: true

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ rhel_release }}"
    state: present

- name: Install EPEL (RHEL 9)
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_release }}.noarch.rpm"
    state: present

- name: Install libev-devel
  ansible.builtin.dnf:
    name:
      - libevent
      - libev-devel
      - flexiblas-devel
      - libtirpc-devel
    state: present
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == "9"


# 2) Install dependencies
- name: Install | dependencies
  ansible.builtin.dnf:
    name: "{{ rstudio_connect_dependencies }}"
    state: "{{ package_install_state | default('latest') }}"
    update_cache: true
  tags:
    - rstudio-connect-install-dependencies

# 3) Install additional packages
- name: Install | additional
  ansible.builtin.dnf:
    name: "{{ rstudio_connect_install }}"
    state: "{{ package_install_state | default('latest') }}"
  tags:
    - rstudio-connect-install-additional

# 4) Create (download) directory
- name: Install | create (download) directory
  ansible.builtin.file:
    path: "{{ rstudio_connect_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - rstudio-connect-install-download
    - rstudio-connect-install-download-directory

# 5) Download RStudio Connect RPM (parametric)
- name: Install | download rpm
  ansible.builtin.get_url:
    url: "{{ rstudio_connect_download_url }}"
    dest: "{{ rstudio_connect_downloads_path }}/rstudio-connect-{{ rstudio_connect_version }}.rpm"
    mode: '0644'
  tags:
    - rstudio-connect-install-download

# 6) Install RStudio Connect RPM (parametric)
- name: Install | install rpm
  ansible.builtin.dnf:
    name: "{{ rstudio_connect_downloads_path }}/rstudio-connect-{{ rstudio_connect_version }}.rpm"
    disable_gpg_check: true
    state: present
  tags:
    - rstudio-connect-install-install
    - rstudio-connect-install-install-rpm
  notify: Restart rstudio-connect
