---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * 3'
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: pip install ansible-lint[community,yamllint]

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ github.repository }}"
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: default
            distro: ubuntu2004
          - scenario: with-python
            distro: ubuntu2004
          - scenario: default
            distro: ubuntu2204
          - scenario: with-python
            distro: ubuntu2204
          - scenario: default
            distro: rockylinux9

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule tests
        run: |
          molecule test -s "${{ matrix.scenario }}"
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_VERBOSITY: '2'
          MOLECULE_DEBUG: '1'
          MOLECULE_DISTRO: "${{ matrix.distro }}"
          PY_COLORS: '1'
        continue-on-error: true  # Continue even if the tests fail to capture logs

      - name: Display RStudio Connect logs on failure
        if: always()  # Only run if the previous step failed
        run: |
          echo "::group::RStudio Connect Status"
          sudo systemctl status rstudio-connect || true
          echo "::endgroup::"

          echo "::group::RStudio Connect Logs"
          sudo journalctl -xeu rstudio-connect || true
          echo "::endgroup::"

      - name: Fail if Molecule tests failed
        if: steps.molecule.outcome == 'failure'
        run: exit 1
